# Generated by Django 4.1.2 on 2022-11-10 07:16

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_gg_crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qclusterrunningtask',
            name='args',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='qclusterrunningtask',
            name='kwargs',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
