# Generated by Django 4.1.2 on 2022-11-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gg_crawl', '0002_alter_qclusterrunningtask_args_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGGSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('key_list', models.TextField()),
                ('key_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Test GG search',
            },
        ),
    ]
