# Generated by Django 4.1.2 on 2022-11-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gg_crawl', '0003_testggsearchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testggsearchmodel',
            name='key_data',
            field=models.JSONField(null=True),
        ),
    ]
