# Generated by Django 4.1.2 on 2022-11-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gg_crawl', '0005_testsavedata_remove_qclusterrunningtask_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QClusterRunningTask',
        ),
    ]
