# Generated by Django 4.1.2 on 2022-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylistmodel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
