# Generated by Django 4.1.2 on 2022-10-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0002_alter_proxylistmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylistmodel',
            name='region',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='proxylistmodel',
            name='country',
            field=models.CharField(choices=[('VN', 'Việt Nam'), ('USA', 'Hoa Kỳ')], default='VN', max_length=125),
            preserve_default=False,
        ),
    ]
