# Generated by Django 4.1.2 on 2022-10-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0003_proxylistmodel_region_alter_proxylistmodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='runingProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.TextField()),
            ],
        ),
    ]
