# Generated by Django 4.1.2 on 2022-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0004_runingproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='runingProxy',
        ),
        migrations.RenameField(
            model_name='proxylistmodel',
            old_name='data',
            new_name='proxies',
        ),
        migrations.AddField(
            model_name='proxylistmodel',
            name='dead_proxies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxylistmodel',
            name='running_proxies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
