# Generated by Django 4.1.2 on 2022-11-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0005_delete_runingproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylistmodel',
            name='dead_proxies',
            field=models.JSONField(default={'data': []}),
        ),
        migrations.AlterField(
            model_name='proxylistmodel',
            name='running_proxies',
            field=models.JSONField(default={'data': []}),
        ),
    ]
