# Generated by Django 4.1.2 on 2022-11-26 02:46

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_selenium', '0006_alter_proxylistmodel_dead_proxies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QClusterRunningTask',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('func', models.CharField(max_length=256)),
                ('hook', models.CharField(max_length=256, null=True)),
                ('args', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('kwargs', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
